Dokumentation
=============
Version 1.1, 26.09.2016
:toc:

== Anforderungen

* Verschlüsseln
** Daten können verschlüsselt gespeichert werden
* Entschlüsseln
** Verschlüsselte Daten können entschlüsselt werden
* Applikation ist über ein Login gesichert

=== Teamübergreifend
Die verschlüsselten Dateien der beiden Teams müssen vom jeweils anderen Team entschlüsselt werden können.
Daher wird ein zentraler link::http://prettysecurecloud.azurewebsites.net/LoginService.svc[Login-Server] verwendet, welcher die verschlüsslungs-Keys und Dienste verwaltet.
Der Aufbau ist wie folgt:

[uml]
--
hide members

frame Client {
    node "C# Mobile Client" as Csharp
    node "Java Desktop Client" as Java
}

frame Server {
    node Datenbank as DB
    node "Login Server" as Login
}

cloud "Cloud Dienst" as Cloud

Csharp --> Login
Java --> Login

Csharp -up-> Cloud
Java -up-> Cloud

Login --> DB

--

== Tools

=== Entwicklung
link:https://www.visualstudio.com/[Visual Studio 2015]
link:https://www.jetbrains.com/resharper/[ReSharper]
link:https://www.xamarin.com/[Xamarin]
link:https://www.xamarin.com/studio[Xamarin Studio]

=== Dokumentation
link:http://asciidocfx.com/[AsciiDocFX]
link:http://de.plantuml.com/[PlantUML]
link:http://www.graphviz.org/[GraphViz]

=== Mockup
link:https://balsamiq.com/products/mockups/[Balsamiq Mockups 3]

== Framework

=== C#
Wir werden C#6 verwenden. Das Projekt wird als Xamarin-Applikation umgesetzt.

==== Xamarin
Damit die Applikation auf mobilen Geräten installiert werden kann, wird das Xamarin-Framework verwendet.

== Datenstruktur

=== Aufbau des Projektordner
Die Dateien werden in verschiedene Ordner (Namespaces) unterteilt. Diese werden nach Verwendungszweck unterteilt.
Das Testprojekt testet lediglich die Logik-Komponente (.core). Die Plattformspezifischen Projekte enthalten nur GUI-Relevanten Code!


[tree]
--
Project Root
|-- PrettySecureCloud.sln
|-- PrettySecureCloud
|   |-- PrettySecureCloud.Core.csproj
|   |   `-- Modules
|   |      `-- ExampleModule.cs
|   |--PrettySecureCloud.Test.csproj
|   |   `-- Modules
|   |      `-- ExampleModuleTest.cs
|   |-- PrettySecureCloud.Android.csproj
|   `-- PrettySecureCloud.iOS.csproj
`-- Dokumentation
--

== VCS-Server
=== link:https://github.com/PascalHonegger/PrettySecureCloud[Client]
C#-Xamarin-Client. Verantwortlich für die Darstellung und das Verwalten der Daten.

=== link:https://github.com/PascalHonegger/PrettySecureCloud_Server[Server]
C#-WCF-Server. Verantwortlich für das Login und speichern der Keys (Dienste-Login). Wird von beiden Teams verwendet!

== Scrum
=== link:https://tree.taiga.io/project/starlordthecoder-cloud-project/backlog[Taiga]
Unsere Scrum-Stories werden auf Taiga verwaltet.

== Architektur
=== Cloud-Dienst
Cloud-Dienste müssen so gekaptselt sein, dass der selbe Code für alle verwendet werden kann.
So wird unsere Applikation nur auf Dropbox ausgelegt sein, trotzdem wird die Implementation durch diverse Schnittstellen gekapselt.
Daher sollte die Einbindung eines weiteren Dienstes wie OneDrive keinen Aufwand bedueten, ausser die Einbindung von OneDrive.
Dateiexplorer und weiteres verfügt über eine lose Kopplung.

[uml]
--

interface IFile {
    +FileName: string
    +FileType: string
    +Path: string
}

class CloudServiceTypeMapper<Static> {
    +static IsSupported(this CloudServiceType type): bool
    +static ToICloudService(this CloudServiceType type): ICloudService
    +static ToICloudService(this CloudService type): ICloudService
}

interface ICloudService {
    +CustomName: string
    +Type: CloudServiceType
    +FileStructure: IEnumerable<IFile>
    +AuthenticateLoginToken(): string
    +UploadFile(FileStream source, IFile target): void
    +DownloadFile(IFile target): FileStream
}

class AddCloudServiceViewModel {
    SelectedServiceType: CloudServiceType
    AddCloudService(): void
}

class FileExplorerViewModel {
    +Files: IEnumerable<IFile>
    +SelectedFile: IFile
    +CloudService: ICloudService
}

class CloudServicesViewModel {
    +CloudServices: IEnumerable<ICloudService>
}

AddCloudServiceViewModel --o CloudServiceTypeMapper
FileExplorerViewModel --o IFile
FileExplorerViewModel --o ICloudService
CloudServicesViewModel --* ICloudService
CloudServicesViewModel --* AddCloudServiceViewModel
CloudServicesViewModel --* FileExplorerViewModel
ICloudService --* IFile
CloudServiceTypeMapper --* ICloudService

--