//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace PrettySecureCloud.Service_References.LoginService {
	[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PrettySecureCloud.Model")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] EncryptionKeyField;
        
        private int IdField;
        
        private string MailField;
        
        private System.Collections.Generic.List<CloudService> ServicesField;
        
        private string UsernameField;
        
        [DataMember()]
        public byte[] EncryptionKey {
            get {
                return this.EncryptionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptionKeyField, value) != true)) {
                    this.EncryptionKeyField = value;
                    this.RaisePropertyChanged("EncryptionKey");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<CloudService> Services {
            get {
                return this.ServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesField, value) != true)) {
                    this.ServicesField = value;
                    this.RaisePropertyChanged("Services");
                }
            }
        }
        
        [DataMember()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="CloudService", Namespace="http://schemas.datacontract.org/2004/07/PrettySecureCloud.Model")]
    public partial class CloudService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string LoginTokenField;
        
        private string NameField;
        
        private ServiceType TypeField;
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public string LoginToken {
            get {
                return this.LoginTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginTokenField, value) != true)) {
                    this.LoginTokenField = value;
                    this.RaisePropertyChanged("LoginToken");
                }
            }
        }
        
        [DataMember()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public ServiceType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ServiceType", Namespace="http://schemas.datacontract.org/2004/07/PrettySecureCloud.Model")]
    public partial class ServiceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string KeyField;
        
        private string NameField;
        
        private string SecretField;
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [DataMember()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public string Secret {
            get {
                return this.SecretField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretField, value) != true)) {
                    this.SecretField = value;
                    this.RaisePropertyChanged("Secret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/UsernameUnique", ReplyAction="http://tempuri.org/ILoginService/UsernameUniqueResponse")]
        System.IAsyncResult BeginUsernameUnique(string username, System.AsyncCallback callback, object asyncState);
        
        bool EndUsernameUnique(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/EmailUnique", ReplyAction="http://tempuri.org/ILoginService/EmailUniqueResponse")]
        System.IAsyncResult BeginEmailUnique(string mail, System.AsyncCallback callback, object asyncState);
        
        bool EndEmailUnique(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/Register", ReplyAction="http://tempuri.org/ILoginService/RegisterResponse")]
        System.IAsyncResult BeginRegister(string username, string mail, string password, System.AsyncCallback callback, object asyncState);
        
        void EndRegister(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/Login", ReplyAction="http://tempuri.org/ILoginService/LoginResponse")]
        System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState);
        
        User EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/ChangePassword", ReplyAction="http://tempuri.org/ILoginService/ChangePasswordResponse")]
        System.IAsyncResult BeginChangePassword(int userId, string currentPassword, string newPassword, System.AsyncCallback callback, object asyncState);
        
        void EndChangePassword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/AddService", ReplyAction="http://tempuri.org/ILoginService/AddServiceResponse")]
        System.IAsyncResult BeginAddService(int userId, ServiceType type, string name, string loginToken, System.AsyncCallback callback, object asyncState);
        
        CloudService EndAddService(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/UpdateService", ReplyAction="http://tempuri.org/ILoginService/UpdateServiceResponse")]
        System.IAsyncResult BeginUpdateService(int userId, int serviceId, string newName, string newLoginToken, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateService(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/RemoveService", ReplyAction="http://tempuri.org/ILoginService/RemoveServiceResponse")]
        System.IAsyncResult BeginRemoveService(int userId, int serviceId, System.AsyncCallback callback, object asyncState);
        
        void EndRemoveService(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginService/LoadAllServices", ReplyAction="http://tempuri.org/ILoginService/LoadAllServicesResponse")]
        System.IAsyncResult BeginLoadAllServices(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<ServiceType> EndLoadAllServices(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsernameUniqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UsernameUniqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailUniqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EmailUniqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CloudService Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CloudService)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadAllServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoadAllServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<ServiceType> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<ServiceType>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<ILoginService>, ILoginService {
        
        private BeginOperationDelegate onBeginUsernameUniqueDelegate;
        
        private EndOperationDelegate onEndUsernameUniqueDelegate;
        
        private System.Threading.SendOrPostCallback onUsernameUniqueCompletedDelegate;
        
        private BeginOperationDelegate onBeginEmailUniqueDelegate;
        
        private EndOperationDelegate onEndEmailUniqueDelegate;
        
        private System.Threading.SendOrPostCallback onEmailUniqueCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegisterDelegate;
        
        private EndOperationDelegate onEndRegisterDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangePasswordDelegate;
        
        private EndOperationDelegate onEndChangePasswordDelegate;
        
        private System.Threading.SendOrPostCallback onChangePasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddServiceDelegate;
        
        private EndOperationDelegate onEndAddServiceDelegate;
        
        private System.Threading.SendOrPostCallback onAddServiceCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateServiceDelegate;
        
        private EndOperationDelegate onEndUpdateServiceDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateServiceCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveServiceDelegate;
        
        private EndOperationDelegate onEndRemoveServiceDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveServiceCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoadAllServicesDelegate;
        
        private EndOperationDelegate onEndLoadAllServicesDelegate;
        
        private System.Threading.SendOrPostCallback onLoadAllServicesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LoginServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LoginServiceClient.GetBindingForEndpoint(endpointConfiguration), LoginServiceClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public LoginServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoginServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public LoginServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoginServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<UsernameUniqueCompletedEventArgs> UsernameUniqueCompleted;
        
        public event System.EventHandler<EmailUniqueCompletedEventArgs> EmailUniqueCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RegisterCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ChangePasswordCompleted;
        
        public event System.EventHandler<AddServiceCompletedEventArgs> AddServiceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateServiceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RemoveServiceCompleted;
        
        public event System.EventHandler<LoadAllServicesCompletedEventArgs> LoadAllServicesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginUsernameUnique(string username, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUsernameUnique(username, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool ILoginService.EndUsernameUnique(System.IAsyncResult result) {
            return base.Channel.EndUsernameUnique(result);
        }
        
        private System.IAsyncResult OnBeginUsernameUnique(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return ((ILoginService)(this)).BeginUsernameUnique(username, callback, asyncState);
        }
        
        private object[] OnEndUsernameUnique(System.IAsyncResult result) {
            bool retVal = ((ILoginService)(this)).EndUsernameUnique(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUsernameUniqueCompleted(object state) {
            if ((this.UsernameUniqueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UsernameUniqueCompleted(this, new UsernameUniqueCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UsernameUniqueAsync(string username) {
            this.UsernameUniqueAsync(username, null);
        }
        
        public void UsernameUniqueAsync(string username, object userState) {
            if ((this.onBeginUsernameUniqueDelegate == null)) {
                this.onBeginUsernameUniqueDelegate = new BeginOperationDelegate(this.OnBeginUsernameUnique);
            }
            if ((this.onEndUsernameUniqueDelegate == null)) {
                this.onEndUsernameUniqueDelegate = new EndOperationDelegate(this.OnEndUsernameUnique);
            }
            if ((this.onUsernameUniqueCompletedDelegate == null)) {
                this.onUsernameUniqueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUsernameUniqueCompleted);
            }
            base.InvokeAsync(this.onBeginUsernameUniqueDelegate, new object[] {
                        username}, this.onEndUsernameUniqueDelegate, this.onUsernameUniqueCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginEmailUnique(string mail, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEmailUnique(mail, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool ILoginService.EndEmailUnique(System.IAsyncResult result) {
            return base.Channel.EndEmailUnique(result);
        }
        
        private System.IAsyncResult OnBeginEmailUnique(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string mail = ((string)(inValues[0]));
            return ((ILoginService)(this)).BeginEmailUnique(mail, callback, asyncState);
        }
        
        private object[] OnEndEmailUnique(System.IAsyncResult result) {
            bool retVal = ((ILoginService)(this)).EndEmailUnique(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEmailUniqueCompleted(object state) {
            if ((this.EmailUniqueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EmailUniqueCompleted(this, new EmailUniqueCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EmailUniqueAsync(string mail) {
            this.EmailUniqueAsync(mail, null);
        }
        
        public void EmailUniqueAsync(string mail, object userState) {
            if ((this.onBeginEmailUniqueDelegate == null)) {
                this.onBeginEmailUniqueDelegate = new BeginOperationDelegate(this.OnBeginEmailUnique);
            }
            if ((this.onEndEmailUniqueDelegate == null)) {
                this.onEndEmailUniqueDelegate = new EndOperationDelegate(this.OnEndEmailUnique);
            }
            if ((this.onEmailUniqueCompletedDelegate == null)) {
                this.onEmailUniqueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEmailUniqueCompleted);
            }
            base.InvokeAsync(this.onBeginEmailUniqueDelegate, new object[] {
                        mail}, this.onEndEmailUniqueDelegate, this.onEmailUniqueCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginRegister(string username, string mail, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegister(username, mail, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ILoginService.EndRegister(System.IAsyncResult result) {
            base.Channel.EndRegister(result);
        }
        
        private System.IAsyncResult OnBeginRegister(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string mail = ((string)(inValues[1]));
            string password = ((string)(inValues[2]));
            return ((ILoginService)(this)).BeginRegister(username, mail, password, callback, asyncState);
        }
        
        private object[] OnEndRegister(System.IAsyncResult result) {
            ((ILoginService)(this)).EndRegister(result);
            return null;
        }
        
        private void OnRegisterCompleted(object state) {
            if ((this.RegisterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterAsync(string username, string mail, string password) {
            this.RegisterAsync(username, mail, password, null);
        }
        
        public void RegisterAsync(string username, string mail, string password, object userState) {
            if ((this.onBeginRegisterDelegate == null)) {
                this.onBeginRegisterDelegate = new BeginOperationDelegate(this.OnBeginRegister);
            }
            if ((this.onEndRegisterDelegate == null)) {
                this.onEndRegisterDelegate = new EndOperationDelegate(this.OnEndRegister);
            }
            if ((this.onRegisterCompletedDelegate == null)) {
                this.onRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterDelegate, new object[] {
                        username,
                        mail,
                        password}, this.onEndRegisterDelegate, this.onRegisterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        User ILoginService.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((ILoginService)(this)).BeginLogin(username, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            User retVal = ((ILoginService)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        public void LoginAsync(string username, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        username,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginChangePassword(int userId, string currentPassword, string newPassword, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangePassword(userId, currentPassword, newPassword, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ILoginService.EndChangePassword(System.IAsyncResult result) {
            base.Channel.EndChangePassword(result);
        }
        
        private System.IAsyncResult OnBeginChangePassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            string currentPassword = ((string)(inValues[1]));
            string newPassword = ((string)(inValues[2]));
            return ((ILoginService)(this)).BeginChangePassword(userId, currentPassword, newPassword, callback, asyncState);
        }
        
        private object[] OnEndChangePassword(System.IAsyncResult result) {
            ((ILoginService)(this)).EndChangePassword(result);
            return null;
        }
        
        private void OnChangePasswordCompleted(object state) {
            if ((this.ChangePasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangePasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangePasswordAsync(int userId, string currentPassword, string newPassword) {
            this.ChangePasswordAsync(userId, currentPassword, newPassword, null);
        }
        
        public void ChangePasswordAsync(int userId, string currentPassword, string newPassword, object userState) {
            if ((this.onBeginChangePasswordDelegate == null)) {
                this.onBeginChangePasswordDelegate = new BeginOperationDelegate(this.OnBeginChangePassword);
            }
            if ((this.onEndChangePasswordDelegate == null)) {
                this.onEndChangePasswordDelegate = new EndOperationDelegate(this.OnEndChangePassword);
            }
            if ((this.onChangePasswordCompletedDelegate == null)) {
                this.onChangePasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangePasswordCompleted);
            }
            base.InvokeAsync(this.onBeginChangePasswordDelegate, new object[] {
                        userId,
                        currentPassword,
                        newPassword}, this.onEndChangePasswordDelegate, this.onChangePasswordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginAddService(int userId, ServiceType type, string name, string loginToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddService(userId, type, name, loginToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudService ILoginService.EndAddService(System.IAsyncResult result) {
            return base.Channel.EndAddService(result);
        }
        
        private System.IAsyncResult OnBeginAddService(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            ServiceType type = ((ServiceType)(inValues[1]));
            string name = ((string)(inValues[2]));
            string loginToken = ((string)(inValues[3]));
            return ((ILoginService)(this)).BeginAddService(userId, type, name, loginToken, callback, asyncState);
        }
        
        private object[] OnEndAddService(System.IAsyncResult result) {
            CloudService retVal = ((ILoginService)(this)).EndAddService(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddServiceCompleted(object state) {
            if ((this.AddServiceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddServiceCompleted(this, new AddServiceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddServiceAsync(int userId, ServiceType type, string name, string loginToken) {
            this.AddServiceAsync(userId, type, name, loginToken, null);
        }
        
        public void AddServiceAsync(int userId, ServiceType type, string name, string loginToken, object userState) {
            if ((this.onBeginAddServiceDelegate == null)) {
                this.onBeginAddServiceDelegate = new BeginOperationDelegate(this.OnBeginAddService);
            }
            if ((this.onEndAddServiceDelegate == null)) {
                this.onEndAddServiceDelegate = new EndOperationDelegate(this.OnEndAddService);
            }
            if ((this.onAddServiceCompletedDelegate == null)) {
                this.onAddServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddServiceCompleted);
            }
            base.InvokeAsync(this.onBeginAddServiceDelegate, new object[] {
                        userId,
                        type,
                        name,
                        loginToken}, this.onEndAddServiceDelegate, this.onAddServiceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginUpdateService(int userId, int serviceId, string newName, string newLoginToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateService(userId, serviceId, newName, newLoginToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ILoginService.EndUpdateService(System.IAsyncResult result) {
            base.Channel.EndUpdateService(result);
        }
        
        private System.IAsyncResult OnBeginUpdateService(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            int serviceId = ((int)(inValues[1]));
            string newName = ((string)(inValues[2]));
            string newLoginToken = ((string)(inValues[3]));
            return ((ILoginService)(this)).BeginUpdateService(userId, serviceId, newName, newLoginToken, callback, asyncState);
        }
        
        private object[] OnEndUpdateService(System.IAsyncResult result) {
            ((ILoginService)(this)).EndUpdateService(result);
            return null;
        }
        
        private void OnUpdateServiceCompleted(object state) {
            if ((this.UpdateServiceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateServiceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateServiceAsync(int userId, int serviceId, string newName, string newLoginToken) {
            this.UpdateServiceAsync(userId, serviceId, newName, newLoginToken, null);
        }
        
        public void UpdateServiceAsync(int userId, int serviceId, string newName, string newLoginToken, object userState) {
            if ((this.onBeginUpdateServiceDelegate == null)) {
                this.onBeginUpdateServiceDelegate = new BeginOperationDelegate(this.OnBeginUpdateService);
            }
            if ((this.onEndUpdateServiceDelegate == null)) {
                this.onEndUpdateServiceDelegate = new EndOperationDelegate(this.OnEndUpdateService);
            }
            if ((this.onUpdateServiceCompletedDelegate == null)) {
                this.onUpdateServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateServiceCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateServiceDelegate, new object[] {
                        userId,
                        serviceId,
                        newName,
                        newLoginToken}, this.onEndUpdateServiceDelegate, this.onUpdateServiceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginRemoveService(int userId, int serviceId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemoveService(userId, serviceId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ILoginService.EndRemoveService(System.IAsyncResult result) {
            base.Channel.EndRemoveService(result);
        }
        
        private System.IAsyncResult OnBeginRemoveService(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            int serviceId = ((int)(inValues[1]));
            return ((ILoginService)(this)).BeginRemoveService(userId, serviceId, callback, asyncState);
        }
        
        private object[] OnEndRemoveService(System.IAsyncResult result) {
            ((ILoginService)(this)).EndRemoveService(result);
            return null;
        }
        
        private void OnRemoveServiceCompleted(object state) {
            if ((this.RemoveServiceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveServiceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveServiceAsync(int userId, int serviceId) {
            this.RemoveServiceAsync(userId, serviceId, null);
        }
        
        public void RemoveServiceAsync(int userId, int serviceId, object userState) {
            if ((this.onBeginRemoveServiceDelegate == null)) {
                this.onBeginRemoveServiceDelegate = new BeginOperationDelegate(this.OnBeginRemoveService);
            }
            if ((this.onEndRemoveServiceDelegate == null)) {
                this.onEndRemoveServiceDelegate = new EndOperationDelegate(this.OnEndRemoveService);
            }
            if ((this.onRemoveServiceCompletedDelegate == null)) {
                this.onRemoveServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveServiceCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveServiceDelegate, new object[] {
                        userId,
                        serviceId}, this.onEndRemoveServiceDelegate, this.onRemoveServiceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ILoginService.BeginLoadAllServices(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoadAllServices(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<ServiceType> ILoginService.EndLoadAllServices(System.IAsyncResult result) {
            return base.Channel.EndLoadAllServices(result);
        }
        
        private System.IAsyncResult OnBeginLoadAllServices(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ILoginService)(this)).BeginLoadAllServices(callback, asyncState);
        }
        
        private object[] OnEndLoadAllServices(System.IAsyncResult result) {
            System.Collections.Generic.List<ServiceType> retVal = ((ILoginService)(this)).EndLoadAllServices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoadAllServicesCompleted(object state) {
            if ((this.LoadAllServicesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoadAllServicesCompleted(this, new LoadAllServicesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoadAllServicesAsync() {
            this.LoadAllServicesAsync(null);
        }
        
        public void LoadAllServicesAsync(object userState) {
            if ((this.onBeginLoadAllServicesDelegate == null)) {
                this.onBeginLoadAllServicesDelegate = new BeginOperationDelegate(this.OnBeginLoadAllServices);
            }
            if ((this.onEndLoadAllServicesDelegate == null)) {
                this.onEndLoadAllServicesDelegate = new EndOperationDelegate(this.OnEndLoadAllServices);
            }
            if ((this.onLoadAllServicesCompletedDelegate == null)) {
                this.onLoadAllServicesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoadAllServicesCompleted);
            }
            base.InvokeAsync(this.onBeginLoadAllServicesDelegate, null, this.onEndLoadAllServicesDelegate, this.onLoadAllServicesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ILoginService CreateChannel() {
            return new LoginServiceClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILoginService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ILoginService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILoginService)) {
                return new System.ServiceModel.EndpointAddress("http://prettysecurecloud.azurewebsites.net/LoginService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ILoginService)) {
                return new System.ServiceModel.EndpointAddress("https://prettysecurecloud.azurewebsites.net/LoginService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private class LoginServiceClientChannel : ChannelBase<ILoginService>, ILoginService {
            
            public LoginServiceClientChannel(System.ServiceModel.ClientBase<ILoginService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginUsernameUnique(string username, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = username;
                System.IAsyncResult _result = base.BeginInvoke("UsernameUnique", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndUsernameUnique(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("UsernameUnique", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEmailUnique(string mail, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = mail;
                System.IAsyncResult _result = base.BeginInvoke("EmailUnique", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndEmailUnique(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("EmailUnique", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRegister(string username, string mail, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = username;
                _args[1] = mail;
                _args[2] = password;
                System.IAsyncResult _result = base.BeginInvoke("Register", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRegister(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Register", _args, result);
            }
            
            public System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public User EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                User _result = ((User)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChangePassword(int userId, string currentPassword, string newPassword, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = userId;
                _args[1] = currentPassword;
                _args[2] = newPassword;
                System.IAsyncResult _result = base.BeginInvoke("ChangePassword", _args, callback, asyncState);
                return _result;
            }
            
            public void EndChangePassword(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ChangePassword", _args, result);
            }
            
            public System.IAsyncResult BeginAddService(int userId, ServiceType type, string name, string loginToken, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = userId;
                _args[1] = type;
                _args[2] = name;
                _args[3] = loginToken;
                System.IAsyncResult _result = base.BeginInvoke("AddService", _args, callback, asyncState);
                return _result;
            }
            
            public CloudService EndAddService(System.IAsyncResult result) {
                object[] _args = new object[0];
                CloudService _result = ((CloudService)(base.EndInvoke("AddService", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateService(int userId, int serviceId, string newName, string newLoginToken, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = userId;
                _args[1] = serviceId;
                _args[2] = newName;
                _args[3] = newLoginToken;
                System.IAsyncResult _result = base.BeginInvoke("UpdateService", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateService(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateService", _args, result);
            }
            
            public System.IAsyncResult BeginRemoveService(int userId, int serviceId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userId;
                _args[1] = serviceId;
                System.IAsyncResult _result = base.BeginInvoke("RemoveService", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRemoveService(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RemoveService", _args, result);
            }
            
            public System.IAsyncResult BeginLoadAllServices(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("LoadAllServices", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<ServiceType> EndLoadAllServices(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<ServiceType> _result = ((System.Collections.Generic.List<ServiceType>)(base.EndInvoke("LoadAllServices", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ILoginService,
            
            BasicHttpsBinding_ILoginService,
        }
    }
}
