Lernjournal Alain Keller
========================
Alain Keller
Version 1.1, 24.10.2016
:toc:

== 20.09.2016, 27.09.2016
An diesen beiden Tagen veruchte ich Xamarin bei mir aufzusetzten. Dies, vor allem die Android VM, war schwerer als gedacht. die Xamarinerweiterung für Visual-Studi war eim einfachsten. Mann muss dafür nur das Programm ändern, xamarin-erweiterung wählen und warten. Lange warten. Im WLan der TBZ kann man gut 2 Stunden dafür rechnen. Jedoch hatte ich am Anfang immer wieder komische Fehler im Code, der eigentlich richtig war, und bei den anderen auch Kompiliert hat. Nach einem Neustart waren sie dann plötzlich wieder Weg. Man konnte vor dem Prohgrammstart eine Münze werfen, ob es Fehler hat oder nicht.
Das Mühsame war dann die Android-VM aufsetzen. Damit die Android-VM lauft, braucht man eine Intel erweiterung. Doch diese konnte nicht Installiert werden, da ich angeblich keine Intel-Virtualisation auf meinem Laptop unterstütze. Danach veruchte ich über Hyper-V eine Android-VM zu erstellen. Da bei WIN-10 nur noch die Pro-Version Hper-V untertützt, musste ich auf Pro upgraden. Zum Glück hatte mein alter Laptop eine Pro-Lizenz und ich koinnte seinen Key brauchen. Doch Hper-V funktionierte immer noch nicht. Nach ein bisschen Googeln fand ich heraus, dass bei einem Upgrade auf die Pro-Version gewisse Teile von Hyper-V nicht richtig funktionieren. Also war diese Option auch gestrichen. 
Später fand ich dann heraus, dass ich die setup-datei der Intel Erweiterung zuerst entzppen muss, damit es erkennt ob ich virtualisation aktiviert habe. Nach langen ausprobieren habe ich es nun entlich geschafft meine Android-VM zum laufen zu bringen. 

== 04.10.2016
=== Skype Online-Meeting
Das Live-Meeting verlief recht gut. Im Vergliech zu einem normalen Meeting sind mir keine Negativen Punkte eingefallen. Das Onlinepoker hat den Teil mit dem abschätzen der Storypoints recht vereinfacht. Was ich jedoch nicht gut fand, war dass ich wegen meinem langen Schulweg früher gehen musste, und durch den Weg eine Stunde verloren ging. Wenn man ein Livemeeting von Zuhause macht, sollte man dann auch zuhause arbeiten können. 

== 24.10.2016
=== Android USB-Debuggging
Alternativ Zur VM kann man  bei android die APP auch direkt auf dem Handy laufen lassen. Das geht über ADB dem Android Debugging tool. Somit kann man das Programm auf dem Handy laufen lassen, und auf dem PC den debugger laufen lassen. Ein weiterer Vorteil ist, dass die App auf den Handy schneller laauft als auf der VM.

== Unterschiede Android-IOS
Im Projekt war ich unter anderem für die Icons zuständig. Es fiel mir auf, dass die Icons im Android viel geordneter im Directory eingebunden sind. Es gibt mehrere ordner, welche die Icons in den verschiedenen grössen enthält. Bei IOS sind jedoch alle in einem Ordner, zur unterscheidung haben sie andere suffixe.
Auch beim Speichern eines Bildes gibt es Unterschiede in der Implementation für IOS und Android. Da wir bis jetzt den ganzen code im allgemeinen Projekt geschriben haben, mussten wir herausfinden wie man Plattformspezifischen code schreiben kann. Pascal und ich haben uns um Andorid gekümmert und Elia für IOS. Damit es möglich ist Plattformspezifischen Code aufzurufen braucht man den DependencyManager. Dieser Kompiliert bei .Droid projekt den Android code und beim .IOS den IOS Code. Die Klassen mit dem Code müssen dan im Plattform eigenen Projekt sein und über 
[source, C#]
----

----[assembly: Dependency(typeof(PictureDroid))]

----
gekennzeichnet werden. SOmit weiss der DependencyManager dass es sich herbei um die Klasse "PictureDroid" handelt. Diese Klasse kann man nun über den DependenyManager im allgemeinen Code aufrufen, und wird beim Kompilieren automatisch der richtigen Plattform zugewiesen.

== Serverprobleme
Unsere Serverappliaktion und Datenbank lauft auf einem Azureserver. Somit kann ich mit meinem Android-Phone von überall unsere Appliaktion nutzen. Als mich Pascal bat die Appliaktion zu testen konnte ich mich nicht mehr einloggen. Der Fehler war, dass die Verbindungen zur Datenbank nach dem schliessen des Apps nie richtig gschlossen wurden. Das heisst, dass obwohl niemand die App zurzeit braucht, immernoch verbindungen zur Datenbank aktiv sind. Das Problem konnte durch ein Using behoben werden. Bei einem Using wird eine gewisse Komponente nur in diesem Teil gebraucht. Nach dem Schliessen des Usings wird auch die Komponente geschlossen, in usnerem Falle die Datenbankverbindung.
